name: Build and Publish Docker Manual

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: yosuga-bot
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: write imageenv file
        shell: bash
        run: |
          cat << EOS > imageenv.json
          {
            "commitId": "${{github.sha}}",
            "ref": "${{github.ref}}",
            "imageName": "${{ env.IMAGE_NAME }}",
            "trigger": "manual"
          }
      #          echo -e "COMMIT_ID=${{ github.sha }}\n" > .imageenv
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
